[package]
name = "atuin-ydoc-convert"
version = "0.0.1"
edition = "2021"

[dependencies]
serde_json = "1.0.138"
roxmltree = "0.20.0"
yrs = "0.22.0"

[dev-dependencies]
json-digest = "0.0.16"
assert-json-diff = "2.0.2"
