name: Rust Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run all checks
        run: |
          set -o pipefail
          EXIT_CODE=0
          cargo test --verbose || EXIT_CODE=$?
          cargo check || EXIT_CODE=$?
          cargo clippy -- -D warnings || EXIT_CODE=$?
          exit $EXIT_CODE
